### ISSUE TITLE
リモートの絵文字を使う機能

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#151]
### Summary

過去にあった機能
```
​:oyasumisskey@misskey.io:​
```
### Purpose

インポートなしで使えたら便利

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kozakura913** [comment]
治安？

**Comment by kozakura913** [comment]
治安の問題があるからモデレーターによる審査とインポート経由でやる
