### ISSUE TITLE
非ログイン時にも公式タグを表示？

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#163]
### Summary

非ログイン時にも公式タグを表示
(よさげな場所がない)

### Purpose

現状 /official-tags を直打ちすれば見れるけど
非ログイン時に公式タグをアピールできたらサーバーの特色がアピールできる？

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kozakura913** [comment]
#317 に統合する
