### ISSUE TITLE
グループに招待されると通知が壊れる

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#192]
### 💡 Summary

グループに招待されると通知が壊れる
大量の通知で流されるか、フィルタすればまた見れる
存在しないエンティティを参照してるらしい

### 🥰 Expected Behavior

通知が見れる

### 🤬 Actual Behavior

通知が見れなくなる

### 📝 Steps to Reproduce

1.グループに招待される
2.通知見る
3.wow

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:4.9.0-beta.2-yojo0.3.1
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [x] Yes, I will patch the bug myself and send a pull request

**Comment by kozakura913** [comment]
例外ハンドリング改善だけでもした方が良さそう
