### ISSUE TITLE
ページ遷移すると稀に無が表示されて何も表示されなくなる

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#197]
### 💡 Summary

ハッシュタグTLを見ようとすると無が表示されて何も表示されなくなる
モバイルのフレンドリー(だったはず)で発生

### 🥰 Expected Behavior

ハッシュタグTLが見れて、他の画面に移動しても見れる

### 🤬 Actual Behavior

ハッシュタグTLが見れない、他の画面に移動しても何も見れない

### 📝 Steps to Reproduce

1.ハッシュタグTLに飛ぶ
2.無
3.移動しても見れない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:4.9.0-beta.2-yojo0.3.2
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kozakura913** [comment]
たぶんこれ
https://github.com/misskey-dev/misskey/pull/14380
