### ISSUE TITLE
ダイスウィジェットのロケールがない

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#274]
### 💡 Summary

ダイスウィジェットのロケールがない

### 🥰 Expected Behavior

ある

### 🤬 Actual Behavior

ない

### 📝 Steps to Reproduce

ウィジェットを開くとない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:4.9.0-yojo0.4.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1673beta** [comment]
こっちのPR引っ張って来てないだろうからないのは当然だよ
https://github.com/1673beta/cherrypick/pull/74
