### ISSUE TITLE
toot:indexableに対応

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#347]
### 概要(Summary)

http://joinmastodon.org/ns#
toot:indexable

https://github.com/mastodon/mastodon/commit/90ec88d58b1342d812810fd91b8e6c3ee84d5a4e

### なぜ必要なのか(Purpose)

見つけられたくない人の投稿が見つかるのはあまり良くないので
対応したい

### 自分で実装しますか？(Do you want to implement this feature yourself?)

- [x] 自分で実装しプルリクエストします(Yes, I will implement this by myself and send a pull request)

**Comment by kozakura913** [comment]
設定>プライバシーからこれ変えられるようにしたい

**Comment by kozakura913** [comment]
indexableのdefaultがfalseだとmisskey系の投稿がほとんど取れない問題が起きそう

**Comment by kozakura913** [comment]
https://codeberg.org/fediverse/fep/src/branch/main/fep/5feb/fep-5feb.md

**Comment by kozakura913** [comment]
https://xn--vusz0j.art/notes/01J77X0WDG50F3DZJNXKG589JF

**Comment by kozakura913** [comment]
pleromaだとこの機能は実装されてないらしい。mastodonで投稿してpleromaで検索できる
