### ISSUE TITLE
リバーシの連合対応状況を連合先に送信し、対応状況をユーザーが簡単に確認できるようにする。

### ISSUE THREAD

**Issue by umipu** [yojo-art/cherrypick#378]
### 概要(Summary)

サーバーがリバーシの連合対戦機能に対応していることをnodeinfoやmetaに埋め込んで連合先に配送する。

受け取ったサーバーは連合リストに何かアイコン等を付けたりする。
リバーシの招待を送る際に非対応サーバーの場合はダイアログを表示する

### なぜ必要なのか(Purpose)

そのサーバーが対応しているかどうかをわざわざソースコード等を見に行かなくて済み、また連合リスト等で可視化されていれば対戦ができるサーバーとそうでないサーバーを簡単に判別ができるため、利便性が向上すると思う。

### 自分で実装しますか？(Do you want to implement this feature yourself?)

- [ ] 自分で実装しプルリクエストします(Yes, I will implement this by myself and send a pull request)

**Comment by kozakura913** [comment]
nodeinfoはある程度古い可能性があるから招待送る時にnodeinfo情報更新した方が良さそう

**Comment by kozakura913** [comment]
フロントエンド追加してから

**Comment by umipu** [comment]
りょ
