### ISSUE TITLE
同じノートを連続でRenoteしようとしたときに警告する機能

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#386]
### 概要(Summary)

自分が最後にリノートしたノートと同じノートをリノートしようとしたら警告する

関連？
https://github.com/Kur0den/cherrypick/issues/7
### なぜ必要なのか(Purpose)

たまにリノートしたの忘れて連打する事がある
リノート確認無効の時に割と事故る

### 自分で実装しますか？(Do you want to implement this feature yourself?)

- [X] 自分で実装しプルリクエストします(Yes, I will implement this by myself and send a pull request)

**Comment by kozakura913** [comment]
目的からしてフロントエンドだけで良さそう
