### ISSUE TITLE
リモートサーバーのチャートの記録に失敗する

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#392]
### 💡 概要(Summary)
リモートサーバーのチャートの記録に失敗する
![image](https://github.com/user-attachments/assets/252a7fdd-6ae7-4f67-9d4f-73f719bf292e)

### 🥰 期待する動作(Expected Behavior)

記録できる

### 🤬 実際の動作(Actual Behavior)

DBエラー
`ERROR:  smallint out of range`

### 📝 再現手順(Steps to Reproduce)
~~いっぱいフォローする~~
~~投稿がいっぱい流れてくる~~
SMALLINT (-32768 ~ 32767)の範囲を超える数のアクティビティが流れてくる

### 💻 動作環境(Frontend Environment)

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 動作環境(サーバー管理者向け)(Backend Environment (for server admin))

```markdown
* Installation Method or Hosting Service:
* CherryPick:4.10.0-rc.3-yojo0.5.2
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### このバグを自分で修正しますか？(Do you want to address this bug yourself?)

- [ ] パッチを作成しプルリクエストします(Yes, I will patch the bug myself and send a pull request)

**Comment by kozakura913** [comment]
リモート/ローカル関係なくチャート格納DBの型で表現できる範囲超えちゃってる
