### ISSUE TITLE
ユーザーのリアクションが表示されない

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#427]
### 💡 概要(Summary)

リアクション壊れた

### 🥰 期待する動作(Expected Behavior)

リアクション履歴が表示される

### 🤬 実際の動作(Actual Behavior)

![Screenshot_20240910_072516_Chrome](https://github.com/user-attachments/assets/e6cf1a26-8dd6-4f0c-9526-c34474e5bb21)

### 📝 再現手順(Steps to Reproduce)

ユーザーメニューに行く
リアクションタブに移動する

### 💻 動作環境(Frontend Environment)

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 動作環境(サーバー管理者向け)(Backend Environment (for server admin))

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### このバグを自分で修正しますか？(Do you want to address this bug yourself?)

- [ ] パッチを作成しプルリクエストします(Yes, I will patch the bug myself and send a pull request)

**Comment by kozakura913** [comment]
なんかいつの間にか壊れてたよねこれ
