### ISSUE TITLE
リモートクリップの説明文に含まれる@がローカル

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#464]
### 💡 概要(Summary)

リモートクリップを開いた時に表示される説明分に含まれる`@user`がそのリモートのユーザーじゃない

### 🥰 期待する動作(Expected Behavior)

リモートのユーザー

### 🤬 実際の動作(Actual Behavior)

ローカルユーザー

### 📝 再現手順(Steps to Reproduce)

説明文にメンションがあるリモートクリップを開く

### 💻 動作環境(Frontend Environment)

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 動作環境(サーバー管理者向け)(Backend Environment (for server admin))

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### このバグを自分で修正しますか？(Do you want to address this bug yourself?)

- [ ] パッチを作成しプルリクエストします(Yes, I will patch the bug myself and send a pull request)

**Comment by kozakura913** [comment]
絵文字もローカル仕様っぽい。まとめて直す
