### ISSUE TITLE
高度な検索でリプライ除外にするとエラーがでる

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#474]
### 💡 概要(Summary)

OpenSearchを利用した高度な検索でリプライ除外をつけるとエラーがでる

### 🥰 期待する動作(Expected Behavior)

検索できる

### 🤬 実際の動作(Actual Behavior)

高度な検索でリプライ除外にするとエラーがでる

### 💻 動作環境(Frontend Environment)

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 動作環境(サーバー管理者向け)(Backend Environment (for server admin))

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### このバグを自分で修正しますか？(Do you want to address this bug yourself?)

- [x] パッチを作成しプルリクエストします(Yes, I will patch the bug myself and send a pull request)

**Comment by kozakura913** [comment]
やっぱテスト必要じゃん
