### ISSUE TITLE
メディアタイムラインの可視性を変更できない

### ISSUE THREAD

**Issue by penginn-net** [yojo-art/cherrypick#54]
### 💡 Summary

画面上部に表示するタイムラインアイコンを
設定/タイムライン　で変更できるが、メディアタイムラインだけできない

![image](https://github.com/yojo-art/cherrypick/assets/121443048/91d6b57e-0c82-457b-9e2c-d78e02a78121)

### 🥰 Expected Behavior

メディアタイムラインも変更できる

### 🤬 Actual Behavior

メディアタイムラインだけ変更できない

### 📝 Steps to Reproduce

設定/タイムラインを開く

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:48aa233e90e042f6a26560e540466fa90553be44
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kozakura913** [comment]
フロント側でGTLから間引いて表示してるだけとか聞いた

**Comment by 1673beta** [comment]
GTLのAPI叩いてフィルターかけてるだけ

**Comment by kozakura913** [comment]
エンドポイント分割の必要がある。あとGTL元に生成してる以上分けるメリットがよくわからん

**Comment by kozakura913** [comment]
次リリースに入れる
