### ISSUE TITLE
【PWA】ノート詳細画面ではリアクションボタンを押してもピッカーが表示されない。

### ISSUE THREAD

**Issue by natumi-kaoru** [yojo-art/cherrypick#596]
### 💡 概要(Summary)

ノート詳細画面ではリアクションボタンを押してもピッカーが表示されない。

### 🥰 期待する動作(Expected Behavior)

ピッカーが表示される。

### 🤬 実際の動作(Actual Behavior)

〃が表示されない。

### 📝 再現手順(Steps to Reproduce)

1. 任意のノートの詳細画面を開く。
2. 🙂を押す。

### 💻 動作環境(Frontend Environment)

```markdown
* Model and OS of the device(s): Xperia 5 III, Android 13 (61.2.A.0.492).
* Browser: Google Chrome.
* Server URL: https://xn--vusz0j.art.
* CherryPick: 1.2.1.
```

### 🛰 動作環境(サーバー管理者向け)(Backend Environment (for server admin))

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### このバグを自分で修正しますか？(Do you want to address this bug yourself?)

- [ ] パッチを作成しプルリクエストします(Yes, I will patch the bug myself and send a pull request)

**Comment by kozakura913** [comment]
#584 で解決されてます(リリース前です)

**Comment by natumi-kaoru** [comment]
> #584 で解決されてます(リリース前です)

承知しました。ありがとうございます。
