### ISSUE TITLE
リモートの添付ファイルの最大解像度が制限される

### ISSUE THREAD

**Issue by penginn-0** [yojo-art/cherrypick#84]
### 💡 Summary

プロキシを使っていると/files/webpublic-...のはずがメディアプロキシのURLになる

### 🥰 Expected Behavior

/files/webpublic-...

### 🤬 Actual Behavior

メディアプロキシのURL

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kozakura913** [comment]
[4ad005](https://github.com/yojo-art/cherrypick/tree/4ad00568796cc78e1ae346d2d7514b92d934c63a) だとこの問題起きてない気がする

**Comment by kozakura913** [comment]
そんなことなかった。default.ymlでメディアプロキシ指定するとそっちに変わるらしい

**Comment by kozakura913** [comment]
たぶんメディアプロキシに飛ばしてる動作は予定された挙動で問題はメディアプロキシが最大解像度を制限してる関係で外部プロキシ使うと生ファイルが見えなくなる

**Comment by kozakura913** [comment]
remoteProxyとかの名称でwebpublicAccessKeyでリモートの生メディア取得できるプロキシURLか何か追加した方が良さそう。
メディアプロキシ指定するとリモートメディアの最大解像度が制限される仕様は不自然だし、mediaProxyは画像しか扱えない

**Comment by 1673beta** [comment]
仕様です

**Comment by kozakura913** [comment]
なんか良い感じ™に出来てきたから後でPR出す
